### ISSUE TITLE
Crash when going to the background

### ISSUE THREAD

**Issue by DongDian455** [FleksySDK/VirtualKeyboardSDK#79] opened 2024-01-08 06:23 UTC
## Environment
- Iphone: 13 pro
- IOS: 15.5
- App/SDK version: 1.0/4.18.2

## Reproduction steps:

1. Run the iOS project and grant keyboard access permission.
2. Open any application and switch to the `FleksySDK keyboard`.
3. Minimize the application and wait for 5 seconds.
4. Return to the application. The `FleksySDK keyboard` crashes, and the system automatically switches to another keyboard.

## SDK Demo Info
![Screenshot 2024-01-08 at 3 47 52 PM](https://github.com/FleksySDK/VirtualKeyboardSDK/assets/30856596/ce82ff87-6090-4680-962a-de73beeae3e5)

## Video
https://github.com/FleksySDK/VirtualKeyboardSDK/assets/30856596/ab2e7fc4-49e7-4038-8b25-af60740e9a65

**Comment by xevifar** [comment] 2024-01-11 08:31
Hello @DongDian455 , 

We cannot validate that this is actually a crash, as we are not able to reproduce this issue. 
If you are debugging the keyboard, could you just use the keyboard without debugging ?

**Comment by DongDian455** [comment] 2024-01-11 09:27
I did not use debug mode. If you are using an **iOS system below version 16**, this issue is expected. 
If there are no crashes, why would the keyboard auto-switch?"

**Comment by xevifar** [comment] 2024-01-11 09:39
Okay, let me pass this to the QA team to try to reproduce it again. Up until now we were not having any luck. 
I'll update you.

**Comment by xevifar** [comment] 2024-01-11 10:20
Hello @DongDian455 , we are able to reproduce it, I will keep you updated with the new release.

**Comment by DongDian455** [comment] 2024-01-11 10:30
Okay, I'll wait for your good news.

**Comment by xevifar** [comment] 2024-01-15 17:14
Hello @DongDian455 , 
This is fixed on the version [4.19.1](https://docs.fleksy.com/sdk-ios/changelog/#v4191)
Please, let me know if this works for you. 

Thank you for the reporting.

**Closed by xevifar** 2024-01-15 17:14 UTC
Labels: bug, iOS

**Comment by DongDian455** [comment] 2024-01-22 07:04
The issue has been resolved in version 4.19.1
